export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as HeroBanner } from "./HeroBanner";
export { default as Exercises } from "./Exercises";
export { default as SearchExercises } from "./SearchExercises";
export { default as Details } from "./Details";
export { default as SimilarExcise } from "./SimilarExcise";
export { default as ExerciseVideo } from "./ExerciseVideo";
export { default as Loader } from "./Loader";
